version: '3'

services:
  thehive:
    image: thehiveproject/thehive:latest
    container_name: thehive
    ports:
      - "9000:9000"
    volumes:
      - thehive-data:/app/data
    environment:
      - ADMIN_PASSWORD=7!Nv2xdgjig342^1Da57FpAeKbA8RQYh
      - JAVA_OPTS=-Xms2g -Xmx2g

volumes:
  thehive-data:
