version: "3.8"

services:
  misp:
    image: misp/misp:latest
    environment:
      MYSQL_PASSWORD: misp
      MYSQL_ROOT_PASSWORD: misp
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      DB_HOST: misp-db
    volumes:
      - ./misp-db:/var/lib/mysql
      - ./misp/app/files:/var/www/MISP/app/files
      - ./misp/app/files/scripts/tmp:/tmp
    depends_on:
      - misp-db
    networks:
      - misp
    ports:
      - "8080:80"
      - "4443:443"

  misp-db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: misp
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: misp
    volumes:
      - ./misp-db:/var/lib/mysql
    networks:
      - misp

  cortex:
    image: thehiveproject/cortex:4.1.3
    volumes:
      - ./cortex:/etc/cortex
    ports:
      - 9001:9001
    depends_on:
      - cortex-db
    networks:
      - thehive

  cortex-db:
    image: postgres:10
    environment:
      POSTGRES_USER: cortex
      POSTGRES_PASSWORD: cortex
      POSTGRES_DB: cortex
    volumes:
      - ./cortex-db:/var/lib/postgresql/data
    networks:
      - thehive

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9300:9200
    networks:
      - thehive

  thehive:
    image: thehiveproject/thehive4:latest
    volumes:
      - ./thehive:/opt/thehive/conf
      - ./thehive/logs:/opt/thehive/logs
    environment:
      - PLAY_APP_SECRET=your_secret_key_here
      - HIVE_ES_NODES=http://elasticsearch:9300
      - HIVE_CORTEX_URL=http://cortex:9001
      - HIVE_CORTEX_PING_URL=http://cortex:9001/ping
    ports:
      - 9000:9000
    depends_on:
      - elasticsearch
      - cortex
    networks:
      - thehive

networks:
  misp:
  thehive:
